### ISSUE TITLE
Does not work when arrow function parameters span multiple lines

### ISSUE THREAD

**Issue by cseickel** [Wansmer/symbol-usage.nvim#14]
In typescript, arrow functions where the parameters include line breaks do not show the usage. For example, this does not work:

``` ts
export const ensureDate = (
  date: Date | string | number | null | undefined,
  timeIfNull: number = -1
): Date => {
  if (date instanceof Date) {
    return date;
  }
  if (typeof date === "string") {
    return new Date(Date.parse(date));
  }
  if (typeof date === "number" && !isNaN(date)) {
    return new Date(date);
  }
  return new Date(timeIfNull);
};
```

but this will:
``` ts
export const ensureDate = ( date: Date | string | number | null | undefined, timeIfNull: number = -1): Date => {
  if (date instanceof Date) {
    return date;
  }
  if (typeof date === "string") {
    return new Date(Date.parse(date));
  }
  if (typeof date === "number" && !isNaN(date)) {
    return new Date(date);
  }
  return new Date(timeIfNull);
};
```

and so will this:
``` ts
export function ensureDate (
  date: Date | string | number | null | undefined,
  timeIfNull: number = -1
): Date {
  if (date instanceof Date) {
    return date;
  }
  if (typeof date === "string") {
    return new Date(Date.parse(date));
  }
  if (typeof date === "number" && !isNaN(date)) {
    return new Date(date);
  }
  return new Date(timeIfNull);
};
```

Is this a simple fix? I would do the work if you could point me in the right direction.

**Comment by Wansmer** [comment]
This is because `tsserver` does not recognize the arrow function in a variable/constant as a `SymbolKind.Function`. (see [#filtering-kinds](https://github.com/Wansmer/symbol-usage.nvim#filtering-kinds)).

I avoid this by setting option `filter_kinds` function, there I check if first line of symbol contains `=>` or `function` (https://github.com/Wansmer/symbol-usage.nvim/blob/f94c2f19152ff44d74efa7521068e454b138faf1/lua/symbol-usage/langs.lua#L4-L11). Technically, it is possible to check all text of symbol, but it can be follow false positive if constant does not contain a function.

E.g., false positive:
```javascript
const withFuncInside = compute(
  () => {}
)
```
If you find better condition to detect functions inside constants, feel free to open a PR.

**Comment by Wansmer** [comment]
I had an idea to do additional checks with treesitter, but haven't gotten around to implementing it yet. In this case you would have to reparse the tree every time the text changes and create a helper to get the node under the position (like [`ts_utils.get_node_at_cursor`](https://github.com/Wansmer/symbol-usage.nvim/blob/f94c2f19152ff44d74efa7521068e454b138faf1/lua/symbol-usage/langs.lua#L4-L11) but for position).

**Comment by cseickel** [comment]
It works now, thanks for fixing so quickly!
