### ISSUE TITLE
Bug: Usage not shown for overloaded methods in C++

### ISSUE THREAD

**Issue by sfc-gh-mjendruk** [Wansmer/symbol-usage.nvim#29]
Hello, thanks for writing this plugin. I noticed an issue with respect to function overloads. In C++ using CLangd, the usage info is only shown for the last overload in a file or class. 

<img width="488" alt="image" src="https://github.com/Wansmer/symbol-usage.nvim/assets/64833375/2ba66e99-f78e-4d90-a07f-5cf95ef1dcb9">

**Comment by Wansmer** [comment]
Hello! 
I have added PR #30, but since I don't write in C++, I can't verify its correctness on a real codebase. 
Could you please check it?
On the example from your issue, it works correctly:

<img width="453" alt="Снимок экрана 2023-11-17 в 05 43 35" src="https://github.com/Wansmer/symbol-usage.nvim/assets/46977173/fc6a75cb-f2b3-4c2a-a573-6fa80d42266f">

After checking the approach on other LSPs, I will add it to the main branch.

**Comment by sfc-gh-mjendruk** [comment]
Hey Ivan, thank you for fixing this. I tried out the fix on my project and it works correctly.

**Comment by Wansmer** [comment]
Great! Done in #30
